### PR TITLE
Readme update (usage in symfony)

### PR DESCRIPTION
**Pull request by dizzy7**

### CODE REVIEW

**Comment by jaimz22** [comment]
check this out...

https://github.com/jaimz22/DoctrineFullTextPostrgresBundle

**Comment by dizzy7** [comment]
Okay, but what is the meaning of this bundle, except readme?

**Comment by jaimz22** [comment]
lol not much at the moment, until I'm able to get back too it.

Either way, I'll checkout your PR's asap! thanks.

**Comment by dzubchik** [comment]
@jaimz22 , ping!

**Comment by jaimz22** [comment]
@dzubchik I just came into some time... I'm working on updating a number of projects, this one is in line (and probably for today)

**Comment by jaimz22** [comment]
This pull request is quite out of date and can't be merged because of the TsVectorSubscriber.php file. So I just copied the changes and made a new commit with the new README.md.

@dizzy7 I gave you credit for the change

**Pull request closed without merging**
