### PR TITLE
Use onFlush event to be able to update on entity changes

### PR DESCRIPTION
**Pull request by teohhanhui**
It was completely broken so far...

### CODE REVIEW

**Comment by markbennett1973** [comment]
@jaimz22 Please can this be merged in - I'm trying to use this bundle in a Symfony 3.2.7 project, and entity updates are not reflected in the full text index at all unless I apply this change.

**Comment by freezlite** [comment]
It will raise error if field nullable, since it copy nullable from original column but onFlush working after query executes. There is my solution https://github.com/jaimz22/DoctrineFullTextPostrgres/pull/14

**Comment by jaimz22** [comment]
This PR was replaced with @freezlite's pr #14

**Pull request closed without merging**
