### PR TITLE
Implemented plainto_tsquery. Fixes #2

### LINKED ISSUE #2: implement plainto_tsquery because to_tsquery don't  accept spaces

### PR DESCRIPTION
**Pull request by Sander-Toonen**
Support for the plainto_tsquery

### CODE REVIEW

**Comment by Vincz** [comment]
Hey @jaimz22 ! Any update about the merging of this PR?

**Comment by jaimz22** [comment]
Yeah this PR looks pretty good, I completely forgot about it. thanks for the reminder

**Comment by Vincz** [comment]
Awesome. Thank you :)

**Comment by Sander-Toonen** [comment]
Lol, I can't remember creating this PR 😛 Thanks for merging!

**Pull request merged**
